dist: trusty
language: php
sudo: required
php:
  - '7.0'
  - '7.1'
 # - '7.2' # Not yet compatible

# don't run for releases
branches:
  except:
  - /^[0-9v]/
  - /^tmp-/

services:
  - mysql
  - docker

addons:
  firefox: latest
  apt:
    sources:
     - google-chrome
    packages:
     - google-chrome-stable fluxbox  

cache:
  directories:
    - node_modules
    - $HOME/.composer/cache/files
    - src/vcslib

before_install:
  - stty cols 80
  - echo "Installing prerequisites..."
  - sudo apt-get update -qq
  - sudo apt-get install -y bibutils zip
  - PHPVERSION=$(phpenv version-name)
  - sudo add-apt-repository -y ppa:ondrej/php && sudo apt-get update
  - sudo apt-get install -y --allow-unauthenticated php${PHPVERSION}-xsl php${PHPVERSION}-intl
  - sudo apt-get install -y yaz libyaz4-dev
  - pear channel-update pear.php.net && yes $'\n' | pecl install yaz && pear install Structures_LinkedList-0.2.2 && pear install File_MARC
  - if php -i | grep yaz --quiet && echo '<?php exit(function_exists("yaz_connect")?0:1);' | php ; then echo "YAZ is installed"; else echo "YAZ installation failed"; exit 1; fi;

install:
  - echo "travis_fold:start:npm_install"
  - echo "Installing dependencies..."
  - if [[ -f package-lock.json ]]; then rm package-lock.json; fi 
#  - rm -rf node_modules
  - npm install npm@latest -g
  - npm install
  - echo "travis_fold:end:npm_install"
  - echo "Installation scripts finished successufully."

before_script:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS tests;'
  - cp build/env/travis/app.conf.toml src/server/config
  # virtual browser support
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3
  - fluxbox >/dev/null 2>&1 &
  
script:
  - npm test

after_success:
  - echo "travis_fold:start:dist_create"
  - npm run dist-create
  - echo "travis_fold:end:dist_create"

deploy:
  provider: script
  script: bash build/env/docker/travis_docker_push.sh
  skip_cleanup: true
  on:
    all_branches: true